/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the IssueArticle service. Represents a row in the &quot;NL_IssueArticle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.newsletter.model.impl.IssueArticleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.newsletter.model.impl.IssueArticleImpl</code>.
 * </p>
 *
 * @author quanhuynhces
 * @see IssueArticle
 * @generated
 */
@ProviderType
public interface IssueArticleModel extends BaseModel<IssueArticle> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a issue article model instance should use the {@link IssueArticle} interface instead.
	 */

	/**
	 * Returns the primary key of this issue article.
	 *
	 * @return the primary key of this issue article
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this issue article.
	 *
	 * @param primaryKey the primary key of this issue article
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this issue article.
	 *
	 * @return the uuid of this issue article
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this issue article.
	 *
	 * @param uuid the uuid of this issue article
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the issue article ID of this issue article.
	 *
	 * @return the issue article ID of this issue article
	 */
	public long getIssueArticleId();

	/**
	 * Sets the issue article ID of this issue article.
	 *
	 * @param issueArticleId the issue article ID of this issue article
	 */
	public void setIssueArticleId(long issueArticleId);

	/**
	 * Returns the issue number of this issue article.
	 *
	 * @return the issue number of this issue article
	 */
	public long getIssueNumber();

	/**
	 * Sets the issue number of this issue article.
	 *
	 * @param issueNumber the issue number of this issue article
	 */
	public void setIssueNumber(long issueNumber);

	/**
	 * Returns the title of this issue article.
	 *
	 * @return the title of this issue article
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this issue article.
	 *
	 * @param title the title of this issue article
	 */
	public void setTitle(String title);

	/**
	 * Returns the author of this issue article.
	 *
	 * @return the author of this issue article
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this issue article.
	 *
	 * @param author the author of this issue article
	 */
	public void setAuthor(String author);

	/**
	 * Returns the order of this issue article.
	 *
	 * @return the order of this issue article
	 */
	public long getOrder();

	/**
	 * Sets the order of this issue article.
	 *
	 * @param order the order of this issue article
	 */
	public void setOrder(long order);

	/**
	 * Returns the content of this issue article.
	 *
	 * @return the content of this issue article
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this issue article.
	 *
	 * @param content the content of this issue article
	 */
	public void setContent(String content);

}